# Generated by Django 5.2.5 on 2025-11-12 17:43

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('name', models.CharField(help_text='Name of the grade', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of the grade')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this grade is currently active')),
            ],
            options={
                'verbose_name': 'Grade',
                'verbose_name_plural': 'Grades',
                'db_table': 'grades',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(default=False, help_text='Whether this record has been soft deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('first_name', models.CharField(help_text='User first name (required)', max_length=150)),
                ('fcm_token', models.TextField(blank=True, help_text='Firebase Cloud Messaging token for push notifications', null=True)),
                ('logged_in_once', models.BooleanField(default=False, help_text='Whether the user has logged in at least once')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
                'db_table': 'accounts',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(default=False, help_text='Whether this record has been soft deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('title', models.CharField(help_text='Title of the competition', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description of the competition')),
                ('code', models.CharField(help_text='Unique code for joining the competition', max_length=10, unique=True)),
                ('competition_type', models.CharField(choices=[('subject', 'Subject Only'), ('subject_with_chapter', 'Subject with Chapter'), ('random', 'Random Questions')], default='subject', help_text='Type of competition', max_length=25)),
                ('total_time', models.PositiveIntegerField(help_text='Total time allowed in minutes')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', help_text='Current status of the competition', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this competition is currently active')),
                ('chapter', models.ForeignKey(blank=True, help_text='Specific chapter for this competition (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competitions', to='subjects.modulechapter')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this competition', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_competitions', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(help_text='Subject for this competition', on_delete=django.db.models.deletion.CASCADE, related_name='competitions', to='subjects.subject')),
            ],
            options={
                'verbose_name': 'Competition',
                'verbose_name_plural': 'Competitions',
                'db_table': 'competitions',
                'ordering': ['-created_at', 'title'],
            },
        ),
        migrations.CreateModel(
            name='CompetitionQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('order', models.PositiveIntegerField(default=1, help_text='Order of the question within the competition')),
                ('points', models.PositiveIntegerField(default=1, help_text='Points awarded for this question')),
                ('competition', models.ForeignKey(help_text='Competition this question belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='competition_questions', to='users.competition')),
                ('question', models.ForeignKey(help_text='Question in this competition', on_delete=django.db.models.deletion.CASCADE, related_name='competition_questions', to='subjects.question')),
            ],
            options={
                'verbose_name': 'Competition Question',
                'verbose_name_plural': 'Competition Questions',
                'db_table': 'competition_questions',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='competition',
            name='questions',
            field=models.ManyToManyField(help_text='Questions included in this competition', related_name='competitions', through='users.CompetitionQuestion', to='subjects.question'),
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('name', models.CharField(help_text='Name of the class', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of the class')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this class is currently active')),
                ('grade', models.ForeignKey(blank=True, help_text='Grade this class belongs to (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='users.grade')),
            ],
            options={
                'verbose_name': 'Class',
                'verbose_name_plural': 'Classes',
                'db_table': 'classes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.PositiveIntegerField(help_text='Level number (1, 2, 3, etc.)', unique=True)),
                ('min_exp', models.PositiveIntegerField(help_text='Minimum experience points required for this level')),
                ('max_exp', models.PositiveIntegerField(help_text='Maximum experience points for this level')),
            ],
            options={
                'verbose_name': 'Level',
                'verbose_name_plural': 'Levels',
                'db_table': 'levels',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['min_exp'], name='level_min_exp_idx'), models.Index(fields=['max_exp'], name='level_max_exp_idx'), models.Index(fields=['name'], name='level_name_idx')],
            },
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(default=False, help_text='Whether this record has been soft deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('title', models.CharField(help_text='Title of the mission', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description of the mission')),
                ('mission_date', models.DateField(help_text='Date when the mission is scheduled')),
                ('exp_multiplier', models.DecimalField(decimal_places=2, default=1.0, help_text='Experience points multiplier for this mission', max_digits=5)),
                ('base_exp', models.PositiveIntegerField(default=10, help_text='Base experience points for completing this mission')),
                ('duration', models.PositiveIntegerField(blank=True, help_text='Duration of the mission in minutes (optional)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this mission is currently active')),
                ('class_group', models.ForeignKey(help_text='Class this mission is assigned to', on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='users.class')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this mission', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_missions', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(blank=True, help_text='Subject this mission is related to (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions', to='subjects.subject')),
            ],
            options={
                'verbose_name': 'Mission',
                'verbose_name_plural': 'Missions',
                'db_table': 'missions',
                'ordering': ['-mission_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='MissionQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('order', models.PositiveIntegerField(default=1, help_text='Order of the question within the mission')),
                ('mission', models.ForeignKey(help_text='Mission this question belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='mission_questions', to='users.mission')),
                ('question', models.ForeignKey(help_text='Question in this mission', on_delete=django.db.models.deletion.CASCADE, related_name='mission_questions', to='subjects.question')),
            ],
            options={
                'verbose_name': 'Mission Question',
                'verbose_name_plural': 'Mission Questions',
                'db_table': 'mission_questions',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='mission',
            name='questions',
            field=models.ManyToManyField(help_text='Questions included in this mission', related_name='missions', through='users.MissionQuestion', to='subjects.question'),
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(default=False, help_text='Whether this record has been soft deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('name', models.CharField(help_text='Name of the school', max_length=200)),
                ('address', models.TextField(blank=True, help_text='Address of the school')),
                ('phone', models.CharField(blank=True, help_text='Phone number of the school', max_length=20)),
                ('email', models.EmailField(blank=True, help_text='Email address of the school', max_length=254)),
                ('website', models.URLField(blank=True, help_text='Website URL of the school')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this school is currently active')),
            ],
            options={
                'verbose_name': 'School',
                'verbose_name_plural': 'Schools',
                'db_table': 'schools',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active'], name='school_is_active_idx'), models.Index(fields=['is_deleted'], name='school_is_deleted_idx'), models.Index(fields=['name'], name='school_name_idx')],
            },
        ),
        migrations.AddField(
            model_name='grade',
            name='school',
            field=models.ForeignKey(help_text='School this grade belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='users.school'),
        ),
        migrations.AddField(
            model_name='class',
            name='school',
            field=models.ForeignKey(help_text='School this class belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='users.school'),
        ),
        migrations.CreateModel(
            name='UserChapterProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('due', 'Due'), ('completed', 'Completed')], default='not_started', help_text='Current status of the user on this chapter', max_length=20)),
                ('percentage', models.PositiveIntegerField(default=0, help_text='Completion percentage of the chapter for this user (0-100)', validators=[django.core.validators.MinValueValidator(0)])),
                ('started_at', models.DateTimeField(blank=True, help_text='When the user first started this chapter', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the user completed this chapter', null=True)),
                ('last_accessed', models.DateTimeField(auto_now=True, help_text='Last time the user accessed this chapter')),
                ('account', models.ForeignKey(help_text='User tracking progress on this chapter', on_delete=django.db.models.deletion.CASCADE, related_name='chapter_progress', to=settings.AUTH_USER_MODEL)),
                ('chapter', models.ForeignKey(help_text='Chapter being tracked', on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='subjects.modulechapter')),
                ('current_question', models.ForeignKey(blank=True, help_text='Current question the user is working on in this chapter', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chapter_progress_current', to='subjects.question')),
            ],
            options={
                'verbose_name': 'User Chapter Progress',
                'verbose_name_plural': 'User Chapter Progress',
                'db_table': 'user_chapter_progress',
                'ordering': ['-last_accessed'],
            },
        ),
        migrations.CreateModel(
            name='UserCompetitionProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', help_text='Current status of the user in this competition', max_length=20)),
                ('score', models.PositiveIntegerField(default=0, help_text='User score in this competition')),
                ('time_taken', models.PositiveIntegerField(default=0, help_text='Time taken in seconds')),
                ('started_at', models.DateTimeField(blank=True, help_text='When the user started this competition', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the user completed this competition', null=True)),
                ('exp_earned', models.PositiveIntegerField(default=0, help_text='Experience points earned from this competition')),
                ('account', models.ForeignKey(help_text='User participating in this competition', on_delete=django.db.models.deletion.CASCADE, related_name='competition_progress', to=settings.AUTH_USER_MODEL)),
                ('competition', models.ForeignKey(help_text='Competition being participated in', on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='users.competition')),
                ('current_question', models.ForeignKey(blank=True, help_text='Current question the user is working on in this competition', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competition_progress_current', to='subjects.question')),
            ],
            options={
                'verbose_name': 'User Competition Progress',
                'verbose_name_plural': 'User Competition Progress',
                'db_table': 'user_competition_progress',
            },
        ),
        migrations.AddField(
            model_name='competition',
            name='participants',
            field=models.ManyToManyField(help_text='Users who joined this competition', related_name='joined_competitions', through='users.UserCompetitionProgress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserMissionProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', help_text='Current status of the user on this mission', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, help_text='When the user first started this mission', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the user completed this mission', null=True)),
                ('exp_earned', models.PositiveIntegerField(default=0, help_text='Experience points earned from this mission')),
                ('account', models.ForeignKey(help_text='User tracking progress on this mission', on_delete=django.db.models.deletion.CASCADE, related_name='mission_progress', to=settings.AUTH_USER_MODEL)),
                ('current_question', models.ForeignKey(blank=True, help_text='Current question the user is working on in this mission', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mission_progress_current', to='subjects.question')),
                ('mission', models.ForeignKey(help_text='Mission being tracked', on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='users.mission')),
            ],
            options={
                'verbose_name': 'User Mission Progress',
                'verbose_name_plural': 'User Mission Progress',
                'db_table': 'user_mission_progress',
            },
        ),
        migrations.CreateModel(
            name='UserModuleProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('due', 'Due'), ('completed', 'Completed')], default='not_started', help_text='Current status of the user on this module', max_length=20)),
                ('percentage', models.PositiveIntegerField(default=0, help_text='Completion percentage of the module for this user (0-100)', validators=[django.core.validators.MinValueValidator(0)])),
                ('started_at', models.DateTimeField(blank=True, help_text='When the user first started this module', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the user completed this module', null=True)),
                ('last_accessed', models.DateTimeField(auto_now=True, help_text='Last time the user accessed this module')),
                ('account', models.ForeignKey(help_text='User tracking progress on this module', on_delete=django.db.models.deletion.CASCADE, related_name='module_progress', to=settings.AUTH_USER_MODEL)),
                ('current_question', models.ForeignKey(blank=True, help_text='Current question the user is working on in this module', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='module_progress_current', to='subjects.question')),
                ('module', models.ForeignKey(help_text='Module being tracked', on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='subjects.module')),
            ],
            options={
                'verbose_name': 'User Module Progress',
                'verbose_name_plural': 'User Module Progress',
                'db_table': 'user_module_progress',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(default=False, help_text='Whether this record has been soft deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('user_type', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('admin', 'Administrator')], default='student', help_text='Type of user in the system', max_length=10)),
                ('admission_number', models.PositiveIntegerField(blank=True, help_text='Unique admission number for the user', null=True, unique=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('roll_number', models.PositiveIntegerField(blank=True, help_text='Roll number for students (must be a positive integer)', null=True, unique=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('total_exp', models.PositiveIntegerField(default=0, help_text='Total experience points earned by solving questions', validators=[django.core.validators.MinValueValidator(0)])),
                ('rewards', models.PositiveIntegerField(default=0, help_text='Total rewards earned by the user', validators=[django.core.validators.MinValueValidator(0)])),
                ('phone_number', models.CharField(blank=True, help_text='User phone number', max_length=15, null=True)),
                ('date_of_birth', models.DateField(blank=True, help_text='User date of birth', null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], help_text='User gender', max_length=20, null=True)),
                ('parent_name', models.CharField(blank=True, help_text='Parent or guardian name for students', max_length=255, null=True)),
                ('profile_picture', models.ImageField(blank=True, help_text='User profile picture', null=True, upload_to='profile_pictures/')),
                ('bio', models.TextField(blank=True, help_text='User biography or description')),
                ('is_class_teacher', models.BooleanField(default=False, help_text='Whether this teacher is a class teacher')),
                ('employee_id', models.CharField(blank=True, help_text='Employee ID for teachers', max_length=50, null=True)),
                ('account', models.OneToOneField(help_text='Account this profile belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('class_instance', models.ForeignKey(blank=True, help_text='Class the user is currently enrolled in', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrolled_students', to='users.class')),
                ('level', models.ForeignKey(blank=True, help_text='Current level of the user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='users.level')),
                ('school', models.ForeignKey(help_text='School the user belongs to (required)', on_delete=django.db.models.deletion.CASCADE, related_name='user_profiles', to='users.school')),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'db_table': 'user_profiles',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_class_teacher', models.BooleanField(default=False, help_text='Whether this teacher is the class teacher for this class')),
                ('class_instance', models.ForeignKey(help_text='Class the teacher is assigned to', on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='users.class')),
                ('subject', models.ForeignKey(help_text='Subject the teacher teaches in this class', on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='subjects.subject')),
                ('teacher', models.ForeignKey(help_text='Teacher (UserProfile) assigned to this class and subject', on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='users.userprofile')),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
                'db_table': 'teachers',
                'ordering': ['teacher', 'class_instance', 'subject'],
            },
        ),
        migrations.AddField(
            model_name='class',
            name='class_teacher',
            field=models.ForeignKey(blank=True, help_text='Class teacher assigned to this class', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes_taught', to='users.userprofile'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['is_active'], name='account_is_active_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['is_deleted'], name='account_is_deleted_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['created_at'], name='account_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['username'], name='account_username_idx'),
        ),
        migrations.AddIndex(
            model_name='competitionquestion',
            index=models.Index(fields=['competition'], name='cq_competition_idx'),
        ),
        migrations.AddIndex(
            model_name='competitionquestion',
            index=models.Index(fields=['question'], name='cq_question_idx'),
        ),
        migrations.AddIndex(
            model_name='competitionquestion',
            index=models.Index(fields=['order'], name='cq_order_idx'),
        ),
        migrations.AddIndex(
            model_name='competitionquestion',
            index=models.Index(fields=['competition', 'order'], name='cq_comp_order_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='competitionquestion',
            unique_together={('competition', 'question')},
        ),
        migrations.AddIndex(
            model_name='missionquestion',
            index=models.Index(fields=['mission'], name='mq_mission_idx'),
        ),
        migrations.AddIndex(
            model_name='missionquestion',
            index=models.Index(fields=['question'], name='mq_question_idx'),
        ),
        migrations.AddIndex(
            model_name='missionquestion',
            index=models.Index(fields=['order'], name='mq_order_idx'),
        ),
        migrations.AddIndex(
            model_name='missionquestion',
            index=models.Index(fields=['mission', 'order'], name='mq_mission_order_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='missionquestion',
            unique_together={('mission', 'question')},
        ),
        migrations.AddIndex(
            model_name='mission',
            index=models.Index(fields=['mission_date'], name='mission_date_idx'),
        ),
        migrations.AddIndex(
            model_name='mission',
            index=models.Index(fields=['is_active'], name='mission_active_idx'),
        ),
        migrations.AddIndex(
            model_name='mission',
            index=models.Index(fields=['is_deleted'], name='mission_deleted_idx'),
        ),
        migrations.AddIndex(
            model_name='mission',
            index=models.Index(fields=['created_by'], name='mission_created_by_idx'),
        ),
        migrations.AddIndex(
            model_name='mission',
            index=models.Index(fields=['class_group'], name='mission_class_idx'),
        ),
        migrations.AddIndex(
            model_name='mission',
            index=models.Index(fields=['subject'], name='mission_subject_idx'),
        ),
        migrations.AddIndex(
            model_name='mission',
            index=models.Index(fields=['mission_date', 'is_active'], name='mission_date_active_idx'),
        ),
        migrations.AddIndex(
            model_name='mission',
            index=models.Index(fields=['class_group', 'is_active'], name='mission_class_active_idx'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['school'], name='grade_school_idx'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['is_active'], name='grade_is_active_idx'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['school', 'is_active'], name='grade_school_active_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userchapterprogress',
            unique_together={('account', 'chapter')},
        ),
        migrations.AddIndex(
            model_name='usercompetitionprogress',
            index=models.Index(fields=['account'], name='ucp_account_idx'),
        ),
        migrations.AddIndex(
            model_name='usercompetitionprogress',
            index=models.Index(fields=['competition'], name='ucp_competition_idx'),
        ),
        migrations.AddIndex(
            model_name='usercompetitionprogress',
            index=models.Index(fields=['status'], name='ucp_status_idx'),
        ),
        migrations.AddIndex(
            model_name='usercompetitionprogress',
            index=models.Index(fields=['score'], name='ucp_score_idx'),
        ),
        migrations.AddIndex(
            model_name='usercompetitionprogress',
            index=models.Index(fields=['account', 'status'], name='ucp_account_status_idx'),
        ),
        migrations.AddIndex(
            model_name='usercompetitionprogress',
            index=models.Index(fields=['competition', 'status'], name='ucp_comp_status_idx'),
        ),
        migrations.AddIndex(
            model_name='usercompetitionprogress',
            index=models.Index(fields=['account', 'competition'], name='ucp_account_comp_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usercompetitionprogress',
            unique_together={('account', 'competition')},
        ),
        migrations.AddIndex(
            model_name='competition',
            index=models.Index(fields=['code'], name='comp_code_idx'),
        ),
        migrations.AddIndex(
            model_name='competition',
            index=models.Index(fields=['competition_type'], name='comp_type_idx'),
        ),
        migrations.AddIndex(
            model_name='competition',
            index=models.Index(fields=['subject'], name='comp_subject_idx'),
        ),
        migrations.AddIndex(
            model_name='competition',
            index=models.Index(fields=['status'], name='comp_status_idx'),
        ),
        migrations.AddIndex(
            model_name='competition',
            index=models.Index(fields=['is_active'], name='comp_active_idx'),
        ),
        migrations.AddIndex(
            model_name='competition',
            index=models.Index(fields=['is_deleted'], name='comp_deleted_idx'),
        ),
        migrations.AddIndex(
            model_name='competition',
            index=models.Index(fields=['created_by'], name='comp_created_by_idx'),
        ),
        migrations.AddIndex(
            model_name='competition',
            index=models.Index(fields=['subject', 'status'], name='comp_subject_status_idx'),
        ),
        migrations.AddIndex(
            model_name='competition',
            index=models.Index(fields=['competition_type', 'status'], name='comp_type_status_idx'),
        ),
        migrations.AddIndex(
            model_name='usermissionprogress',
            index=models.Index(fields=['account'], name='ump_mission_account_idx'),
        ),
        migrations.AddIndex(
            model_name='usermissionprogress',
            index=models.Index(fields=['mission'], name='ump_mission_mission_idx'),
        ),
        migrations.AddIndex(
            model_name='usermissionprogress',
            index=models.Index(fields=['status'], name='ump_mission_status_idx'),
        ),
        migrations.AddIndex(
            model_name='usermissionprogress',
            index=models.Index(fields=['account', 'status'], name='ump_mission_account_status_idx'),
        ),
        migrations.AddIndex(
            model_name='usermissionprogress',
            index=models.Index(fields=['mission', 'status'], name='ump_mission_mission_status_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usermissionprogress',
            unique_together={('account', 'mission')},
        ),
        migrations.AddIndex(
            model_name='usermoduleprogress',
            index=models.Index(fields=['account'], name='ump_account_idx'),
        ),
        migrations.AddIndex(
            model_name='usermoduleprogress',
            index=models.Index(fields=['module'], name='ump_module_idx'),
        ),
        migrations.AddIndex(
            model_name='usermoduleprogress',
            index=models.Index(fields=['status'], name='ump_status_idx'),
        ),
        migrations.AddIndex(
            model_name='usermoduleprogress',
            index=models.Index(fields=['percentage'], name='ump_percentage_idx'),
        ),
        migrations.AddIndex(
            model_name='usermoduleprogress',
            index=models.Index(fields=['account', 'status'], name='ump_account_status_idx'),
        ),
        migrations.AddIndex(
            model_name='usermoduleprogress',
            index=models.Index(fields=['module', 'status'], name='ump_module_status_idx'),
        ),
        migrations.AddIndex(
            model_name='usermoduleprogress',
            index=models.Index(fields=['account', 'module'], name='ump_account_module_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usermoduleprogress',
            unique_together={('account', 'module')},
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['user_type'], name='profile_user_type_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['school'], name='profile_school_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['total_exp'], name='profile_total_exp_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['is_deleted'], name='profile_is_deleted_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['created_at'], name='profile_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['class_instance'], name='profile_class_instance_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['school', 'user_type'], name='profile_school_type_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['teacher'], name='teacher_teacher_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['class_instance'], name='teacher_class_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['subject'], name='teacher_subject_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['is_class_teacher'], name='teacher_is_cls_teach_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['teacher', 'class_instance'], name='teacher_tchr_cls_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['class_instance', 'subject'], name='teacher_cls_subj_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['teacher', 'is_class_teacher'], name='teacher_tchr_clsteach_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='teacher',
            unique_together={('teacher', 'class_instance', 'subject')},
        ),
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['school'], name='class_school_idx'),
        ),
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['is_active'], name='class_is_active_idx'),
        ),
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['class_teacher'], name='class_teacher_idx'),
        ),
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['grade'], name='class_grade_idx'),
        ),
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['school', 'is_active'], name='class_school_active_idx'),
        ),
    ]
