# Generated by Django 5.2.5 on 2025-11-30 17:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_create_student_teacher_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('notification_id', models.CharField(help_text='Unique identifier for this notification', max_length=255)),
                ('data', models.JSONField(blank=True, default=dict, help_text='Notification data payload (JSON)')),
                ('type', models.CharField(choices=[('module', 'Module'), ('subject', 'Subject'), ('user', 'User'), ('mission', 'Mission'), ('competition', 'Competition')], help_text='Type of notification', max_length=20)),
                ('triggered_by', models.CharField(choices=[('auto', 'Auto'), ('user', 'User'), ('manual', 'Manual')], default='auto', help_text='How this notification was triggered', max_length=10)),
                ('is_read', models.BooleanField(default=False, help_text='Whether the notification has been read by the user')),
                ('read_at', models.DateTimeField(blank=True, help_text='Timestamp when the notification was read', null=True)),
                ('user', models.ForeignKey(help_text='User who receives this notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='notification_user_idx'), models.Index(fields=['type'], name='notification_type_idx'), models.Index(fields=['triggered_by'], name='notification_triggered_by_idx'), models.Index(fields=['is_read'], name='notification_is_read_idx'), models.Index(fields=['user', 'is_read'], name='notification_user_read_idx'), models.Index(fields=['user', 'type'], name='notification_user_type_idx'), models.Index(fields=['notification_id'], name='notification_id_idx')],
            },
        ),
    ]
