# Generated by Django 5.2.5 on 2025-12-05 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_notification'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='teacher',
            name='teacher_is_cls_teach_idx',
        ),
        migrations.RemoveIndex(
            model_name='teacher',
            name='teacher_tchr_clsteach_idx',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='is_class_teacher',
        ),
    ]
