# Generated by Django 5.2.5 on 2026-01-13 06:12

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0019_module_due_date_question_hint'),
        ('users', '0006_move_subjects_to_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(default=False, help_text='Whether this record has been soft deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True, help_text='When the test was assigned to the user')),
                ('due_date', models.DateTimeField(blank=True, help_text='Deadline for completing the test', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this test assignment is currently active')),
                ('account', models.ForeignKey(help_text='User assigned to this test', on_delete=django.db.models.deletion.CASCADE, related_name='user_tests', to=settings.AUTH_USER_MODEL)),
                ('assigned_by', models.ForeignKey(blank=True, help_text='Teacher/Admin who assigned this test', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests_assigned', to=settings.AUTH_USER_MODEL)),
                ('mission', models.ForeignKey(help_text='Mission used as the test', on_delete=django.db.models.deletion.CASCADE, related_name='user_tests', to='users.mission')),
            ],
            options={
                'verbose_name': 'User Test',
                'verbose_name_plural': 'User Tests',
                'db_table': 'user_tests',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='UserTestProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='not_started', help_text='Current status of the user on this test', max_length=20)),
                ('percentage', models.PositiveIntegerField(default=0, help_text='Completion percentage of the test (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('score', models.PositiveIntegerField(default=0, help_text='Score achieved in the test')),
                ('total_questions', models.PositiveIntegerField(default=0, help_text='Total number of questions in the test')),
                ('questions_attempted', models.PositiveIntegerField(default=0, help_text='Number of questions attempted')),
                ('correct_answers', models.PositiveIntegerField(default=0, help_text='Number of correct answers')),
                ('wrong_answers', models.PositiveIntegerField(default=0, help_text='Number of wrong answers')),
                ('started_at', models.DateTimeField(blank=True, help_text='When the user started this test', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the user completed this test', null=True)),
                ('last_accessed', models.DateTimeField(auto_now=True, help_text='Last time the user accessed this test')),
                ('time_spent_seconds', models.PositiveIntegerField(default=0, help_text='Total time spent on the test in seconds')),
                ('exp_earned', models.PositiveIntegerField(default=0, help_text='Experience points earned from this test')),
                ('current_question', models.ForeignKey(blank=True, help_text='Current question the user is working on in this test', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_progress_current', to='subjects.question')),
                ('user_test', models.OneToOneField(help_text='The test this progress is tracking', on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='users.usertest')),
            ],
            options={
                'verbose_name': 'User Test Progress',
                'verbose_name_plural': 'User Test Progress',
                'db_table': 'user_test_progress',
            },
        ),
        migrations.AddIndex(
            model_name='usertest',
            index=models.Index(fields=['account'], name='user_test_account_idx'),
        ),
        migrations.AddIndex(
            model_name='usertest',
            index=models.Index(fields=['mission'], name='user_test_mission_idx'),
        ),
        migrations.AddIndex(
            model_name='usertest',
            index=models.Index(fields=['is_active'], name='user_test_active_idx'),
        ),
        migrations.AddIndex(
            model_name='usertest',
            index=models.Index(fields=['is_deleted'], name='user_test_deleted_idx'),
        ),
        migrations.AddIndex(
            model_name='usertest',
            index=models.Index(fields=['due_date'], name='user_test_due_date_idx'),
        ),
        migrations.AddIndex(
            model_name='usertest',
            index=models.Index(fields=['account', 'is_active'], name='user_test_acc_active_idx'),
        ),
        migrations.AddIndex(
            model_name='usertest',
            index=models.Index(fields=['assigned_by'], name='user_test_assigned_by_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usertest',
            unique_together={('account', 'mission')},
        ),
        migrations.AddIndex(
            model_name='usertestprogress',
            index=models.Index(fields=['user_test'], name='utp_user_test_idx'),
        ),
        migrations.AddIndex(
            model_name='usertestprogress',
            index=models.Index(fields=['status'], name='utp_status_idx'),
        ),
        migrations.AddIndex(
            model_name='usertestprogress',
            index=models.Index(fields=['percentage'], name='utp_percentage_idx'),
        ),
        migrations.AddIndex(
            model_name='usertestprogress',
            index=models.Index(fields=['score'], name='utp_score_idx'),
        ),
        migrations.AddIndex(
            model_name='usertestprogress',
            index=models.Index(fields=['completed_at'], name='utp_completed_at_idx'),
        ),
    ]
