# Generated by Django 5.2.5 on 2026-01-29 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0019_module_due_date_question_hint'),
        ('users', '0009_update_mission_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this test', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='test',
            index=models.Index(fields=['created_by'], name='test_created_by_idx'),
        ),
    ]
