# Generated by Django 5.2.5 on 2026-01-30 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_test_created_by_test_test_created_by_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='test_datetime',
            field=models.DateTimeField(help_text='Date and time when the test is scheduled (stored in UTC; API accepts/returns Indian time Asia/Kolkata)'),
        ),
    ]
