# Generated by Django 5.2.5 on 2026-02-02 18:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_add_test_module_chapter_multi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmodulechapter',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False),
        ),
    ]
