# Generated by Django 5.2.5 on 2026-02-28 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0023_modulechapter_due_date'),
        ('users', '0014_add_test_class_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='subjects',
            field=models.ManyToManyField(blank=True, help_text='Subjects this student is enrolled in (students in the same class can have different subjects)', related_name='enrolled_students', to='subjects.subject'),
        ),
    ]
