# Generated by Django 5.2.5 on 2026-02-28 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0023_modulechapter_due_date'),
        ('users', '0015_student_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='subjects',
            field=models.ManyToManyField(blank=True, help_text='Subjects this teacher teaches', related_name='teachers', to='subjects.subject'),
        ),
    ]
