# Generated by Django 5.2.5 on 2026-03-02 19:04

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0025_class_unique_per_school_mission_unique_per_day'),
        ('users', '0017_clean_schema'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='studentsubjectenrollment',
            name='sse_student_subject_unique',
        ),
        migrations.AlterField(
            model_name='student',
            name='admission_number',
            field=models.PositiveIntegerField(blank=True, help_text='Admission number — unique within a school, not globally', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_number',
            field=models.PositiveIntegerField(blank=True, help_text='Roll number — unique within a class, not globally', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='studentsubjectenrollment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created'),
        ),
        migrations.AlterField(
            model_name='studentsubjectenrollment',
            name='enrolled_by',
            field=models.ForeignKey(blank=True, help_text='Admin/teacher who created this enrollment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentsubjectenrollment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='studentsubjectenrollment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated'),
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('name', 'school')},
        ),
        migrations.AlterUniqueTogether(
            name='mission',
            unique_together={('account', 'mission_date', 'subject')},
        ),
        migrations.AlterUniqueTogether(
            name='studentsubjectenrollment',
            unique_together={('student', 'subject')},
        ),
    ]
