# Generated by Django 5.2.5 on 2026-03-08 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_class_unique_per_school_mission_unique_per_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('administrator', 'Administrator')], default='student', help_text='Type of user in the system', max_length=15),
        ),
    ]
