# Generated by Django 5.2.5 on 2026-03-29 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_rename_admin_to_administrator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('module', 'Module'), ('subject', 'Subject'), ('user', 'User'), ('mission', 'Mission'), ('competition', 'Competition'), ('test', 'Test')], help_text='Type of notification', max_length=20),
        ),
    ]
