# Generated by Django 5.2.5 on 2026-04-15 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_add_test_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='password_prefix',
            field=models.CharField(blank=True, help_text="Prefix used when generating passwords for this school's users", max_length=20),
        ),
    ]
