# Generated by Django 5.2.5 on 2025-11-12 17:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('name', models.CharField(help_text='Name of the module', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of the module')),
                ('order', models.PositiveIntegerField(default=1, help_text='Order of the module within the subject')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this module is currently active')),
                ('logo', models.ImageField(blank=True, help_text='Logo image for the module', null=True, upload_to='module_logos/')),
                ('is_enabled', models.BooleanField(default=False, help_text='Whether this module is enabled for use')),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': 'Modules',
                'db_table': 'modules',
                'ordering': ['subject', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ModuleChapter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(default=False, help_text='Whether this record has been soft deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('title', models.CharField(help_text='Title of the chapter', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description of the chapter')),
                ('order', models.PositiveIntegerField(default=1, help_text='Order of the chapter within the module')),
                ('is_enabled', models.BooleanField(default=True, help_text='Whether this chapter is currently enabled')),
                ('is_important', models.BooleanField(default=False, help_text='Whether this chapter is marked as important')),
                ('logo', models.ImageField(blank=True, help_text='Logo image for the chapter', null=True, upload_to='chapter_logos/')),
            ],
            options={
                'verbose_name': 'Module Chapter',
                'verbose_name_plural': 'Module Chapters',
                'db_table': 'module_chapters',
                'ordering': ['module', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ModuleContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(default=False, help_text='Whether this record has been soft deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('content_type', models.CharField(choices=[('question', 'Question'), ('theory', 'Theory')], help_text='Type of content (question or theory)', max_length=20)),
                ('order', models.PositiveIntegerField(default=1, help_text='Order of this content within the chapter')),
            ],
            options={
                'verbose_name': 'Module Content',
                'verbose_name_plural': 'Module Contents',
                'db_table': 'module_contents',
                'ordering': ['chapter', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('option_text', models.CharField(help_text='The option text', max_length=500)),
                ('is_correct', models.BooleanField(default=False, help_text='Whether this option is correct')),
                ('order', models.PositiveIntegerField(default=1, help_text='Order of the option within the question')),
            ],
            options={
                'verbose_name': 'Option',
                'verbose_name_plural': 'Options',
                'db_table': 'options',
                'ordering': ['question', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(default=False, help_text='Whether this record has been soft deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('question_text', models.TextField(help_text='The question text')),
                ('image', models.ImageField(blank=True, help_text='Optional image for the question', null=True, upload_to='question_images/')),
                ('question_type', models.CharField(choices=[('mcq_single', 'MCQ - Single Correct Answer'), ('mcq_multiple', 'MCQ - Multiple Correct Answers'), ('short_answer', 'Short Answer Question')], default='mcq_single', help_text='Type of question', max_length=20)),
                ('exp_points', models.PositiveIntegerField(default=10, help_text='Experience points awarded for correct answer')),
                ('difficulty_level', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', help_text='Difficulty level of the question', max_length=10)),
                ('explanation', models.TextField(blank=True, help_text='Explanation for the correct answer')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this question is currently active')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'db_table': 'questions',
                'ordering': ['difficulty_level', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('name', models.CharField(help_text='Name of the subject', max_length=100, unique=True)),
                ('code', models.CharField(help_text='Short code for the subject', max_length=10, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the subject')),
                ('logo', models.ImageField(help_text='Logo image for the subject', upload_to='subject_logos/')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this subject is currently active')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'db_table': 'subjects',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Theory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(default=False, help_text='Whether this record has been soft deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('title', models.CharField(help_text='Title of the theory content', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the theory')),
            ],
            options={
                'verbose_name': 'Theory',
                'verbose_name_plural': 'Theories',
                'db_table': 'theories',
                'ordering': ['title'],
            },
        ),
    ]
