# Generated by Django 5.2.5 on 2025-11-12 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this module', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_modules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='modulechapter',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this chapter', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='modulechapter',
            name='module',
            field=models.ForeignKey(help_text='Module this chapter belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='subjects.module'),
        ),
        migrations.AddField(
            model_name='modulecontent',
            name='chapter',
            field=models.ForeignKey(help_text='Chapter this content belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='subjects.modulechapter'),
        ),
        migrations.AddField(
            model_name='modulecontent',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this content', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_module_contents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this question', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='option',
            name='question',
            field=models.ForeignKey(help_text='Question this option belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='options', to='subjects.question'),
        ),
        migrations.AddField(
            model_name='modulecontent',
            name='question',
            field=models.ForeignKey(blank=True, help_text='Question if content_type is "question"', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module_contents', to='subjects.question'),
        ),
        migrations.AddField(
            model_name='subject',
            name='classes',
            field=models.ManyToManyField(blank=True, help_text='Classes that study this subject', related_name='subjects', to='users.class'),
        ),
        migrations.AddField(
            model_name='subject',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this subject', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_subjects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='module',
            name='subject',
            field=models.ForeignKey(help_text='Subject this module belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='subjects.subject'),
        ),
        migrations.AddField(
            model_name='theory',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this theory', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_theories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='modulecontent',
            name='theory',
            field=models.ForeignKey(blank=True, help_text='Theory if content_type is "theory"', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module_contents', to='subjects.theory'),
        ),
        migrations.AlterUniqueTogether(
            name='modulechapter',
            unique_together={('module', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='option',
            unique_together={('question', 'option_text')},
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['is_active'], name='subject_is_active_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['name'], name='subject_name_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['code'], name='subject_code_idx'),
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['subject'], name='module_subject_idx'),
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['order'], name='module_order_idx'),
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['is_active'], name='module_is_active_idx'),
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['is_enabled'], name='module_is_enabled_idx'),
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['subject', 'order'], name='module_subject_order_idx'),
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['subject', 'is_active'], name='module_subject_active_idx'),
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['subject', 'is_enabled'], name='module_subject_enabled_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='module',
            unique_together={('subject', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='modulecontent',
            unique_together={('chapter', 'order')},
        ),
    ]
