# Generated by Django 5.2.5 on 2025-11-13 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo image for the module', null=True, upload_to='module_logos/'),
        ),
        migrations.AlterField(
            model_name='modulechapter',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo image for the chapter', null=True, upload_to='chapter_logos/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional image for the question', null=True, upload_to='question_images/'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='logo',
            field=models.ImageField(help_text='Logo image for the subject', upload_to='subject_logos/'),
        ),
    ]
