# Generated by Django 5.2.5 on 2025-11-27 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0004_alter_module_logo_alter_modulechapter_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='color',
            field=models.CharField(default='0DA6F2', help_text='Hex color code for the subject (without #)', max_length=6),
        ),
    ]
