# Generated by Django 5.2.5 on 2025-11-27 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0006_alter_subject_options_subject_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='logo_url',
            field=models.URLField(blank=True, help_text='Logo URL for the module (enter URL directly)'),
        ),
        migrations.AddField(
            model_name='subject',
            name='logo_url',
            field=models.URLField(blank=True, help_text='Logo URL for the subject (enter URL directly)'),
        ),
        migrations.AlterField(
            model_name='module',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo image file for the module (upload file)', null=True, upload_to='module_logos/'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo image file for the subject (upload file)', null=True, upload_to='subject_logos/'),
        ),
    ]
