# Generated by Django 5.2.5 on 2025-11-30 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0007_module_logo_url_subject_logo_url_alter_module_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulechapter',
            name='has_hots',
            field=models.BooleanField(default=False, help_text='Whether this chapter has Higher Order Thinking Skills (HOTS) questions'),
        ),
        migrations.AddField(
            model_name='question',
            name='is_hots',
            field=models.BooleanField(default=False, help_text='Whether this question is a Higher Order Thinking Skills (HOTS) question'),
        ),
    ]
