# Generated by Django 5.2.5 on 2025-11-30 09:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0008_modulechapter_has_hots_question_is_hots'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_correct', models.BooleanField(default=False, help_text='Whether the answer is correct')),
                ('answer', models.TextField(help_text='The answer text provided by the user')),
                ('tries', models.PositiveIntegerField(default=1, help_text='Number of attempts made for this question')),
                ('prev_exp', models.PositiveIntegerField(default=0, help_text='Previous experience points before answering this question')),
                ('current_exp', models.PositiveIntegerField(default=0, help_text='Current experience points after answering this question')),
                ('question', models.ForeignKey(help_text='Question that was answered', on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='subjects.question')),
                ('user', models.ForeignKey(help_text='User who answered the question', on_delete=django.db.models.deletion.CASCADE, related_name='answers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Answer',
                'verbose_name_plural': 'Answers',
                'db_table': 'answers',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='answer_user_idx'), models.Index(fields=['question'], name='answer_question_idx'), models.Index(fields=['user', 'question'], name='answer_user_question_idx'), models.Index(fields=['is_correct'], name='answer_is_correct_idx')],
                'unique_together': {('user', 'question')},
            },
        ),
        migrations.CreateModel(
            name='ChapterHOTS',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('order', models.PositiveIntegerField(default=1, help_text='Order of the HOTS question within the chapter')),
                ('chapter', models.ForeignKey(help_text='Chapter this HOTS question belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='hots_questions', to='subjects.modulechapter')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this HOTS question association', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_chapter_hots', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(help_text='HOTS question for this chapter', on_delete=django.db.models.deletion.CASCADE, related_name='chapter_hots', to='subjects.question')),
            ],
            options={
                'verbose_name': 'Chapter HOTS',
                'verbose_name_plural': 'Chapter HOTS',
                'db_table': 'chapter_hots',
                'ordering': ['chapter', 'order'],
                'indexes': [models.Index(fields=['chapter'], name='chapter_hots_chapter_idx'), models.Index(fields=['question'], name='chapter_hots_question_idx'), models.Index(fields=['chapter', 'order'], name='chapter_hots_chapter_order_idx')],
                'unique_together': {('chapter', 'question')},
            },
        ),
    ]
