# Generated by Django 5.2.5 on 2025-11-30 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0009_answer_chapterhots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='current_exp',
            field=models.PositiveIntegerField(db_column='current_exp', default=0, help_text='Current experience points after answering this question'),
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='current_exp',
            new_name='current_Exp',
        ),
    ]
