# Generated by Django 5.2.5 on 2025-11-30 18:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0010_alter_answer_current_exp_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualVerificationAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('answer', models.TextField(help_text='The answer text provided by the user that needs manual verification')),
                ('question', models.ForeignKey(help_text='Question that was answered', on_delete=django.db.models.deletion.CASCADE, related_name='manual_verification_answers', to='subjects.question')),
                ('user', models.ForeignKey(help_text='User who provided the answer', on_delete=django.db.models.deletion.CASCADE, related_name='manual_verification_answers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Manual Verification Answer',
                'verbose_name_plural': 'Manual Verification Answers',
                'db_table': 'manual_verification_answers',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='mva_user_idx'), models.Index(fields=['question'], name='mva_question_idx'), models.Index(fields=['user', 'question'], name='mva_user_question_idx')],
            },
        ),
    ]
