# Generated by Django 5.2.5 on 2025-12-06 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0011_manualverificationanswer'),
        ('users', '0006_move_subjects_to_class'),  # Data must be migrated first
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='classes',
        ),
    ]
