# Generated by Django 5.2.5 on 2025-12-19 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0012_move_subjects_to_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')], default=1, help_text='Question level (1-5)'),
        ),
    ]
