# Generated by Django 5.2.5 on 2025-12-19 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0013_question_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulechapter',
            name='max_questions',
            field=models.PositiveIntegerField(default=10, help_text='Maximum number of questions to send for this chapter'),
        ),
    ]
