# Generated by Django 5.2.5 on 2025-12-19 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0014_modulechapter_max_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('mcq_single', 'MCQ - Single Correct Answer'), ('mcq_multiple', 'MCQ - Multiple Correct Answers'), ('short_answer', 'Short Answer Question'), ('rearrange', 'Re-arrange')], default='mcq_single', help_text='Type of question', max_length=20),
        ),
    ]
