# Generated by Django 5.2.5 on 2025-12-25 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0015_alter_question_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='from_mission',
            field=models.BooleanField(default=False, help_text='Whether this answer was submitted from a mission'),
        ),
    ]
