# Generated by Django 5.2.5 on 2025-12-26 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0016_add_from_mission_to_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulechapter',
            name='theory',
            field=models.TextField(blank=True, help_text='Theory content for this chapter'),
        ),
    ]
