# Generated by Django 5.2.5 on 2025-12-28 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0017_add_theory_to_modulechapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='ai_generated',
            field=models.BooleanField(default=False, help_text='Whether this question was generated by AI'),
        ),
    ]
