# Generated by Django 5.2.5 on 2026-01-10 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0018_add_ai_generated_to_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='due_date',
            field=models.DateField(blank=True, help_text='Due date for this module', null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='hint',
            field=models.TextField(blank=True, help_text='Hint to help the user answer the question'),
        ),
    ]
