# Generated by Django 5.2.5 on 2026-02-23 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0020_add_test_to_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(help_text='Name of the subject', max_length=100),
        ),
    ]
