# Generated by Django 5.2.5

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0021_alter_subject_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulechapter',
            name='is_due',
            field=models.BooleanField(default=False, help_text='Whether this assignment/chapter is marked as due'),
        ),
    ]
