# Generated by Django 5.2.5

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0022_add_modulechapter_is_due'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulechapter',
            name='due_date',
            field=models.DateField(blank=True, help_text='Due date for this assignment/chapter', null=True),
        ),
    ]
