# Generated by Django 5.2.5 on 2026-03-02 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0024_answer_chapter_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='chapter',
            field=models.ForeignKey(blank=True, help_text='Chapter this answer belongs to (denormalized from question→ModuleContent→chapter for fast dashboard queries)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answers', to='subjects.modulechapter'),
        ),
    ]
