# Generated by Django 5.2.5 on 2026-03-06 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0027_module_class_fk'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['subject', 'class_instance', 'order', 'name'], 'verbose_name': 'Module', 'verbose_name_plural': 'Modules'},
        ),
    ]
