# Generated by Django 5.2.5 on 2026-03-20 11:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0028_alter_module_options'),
        ('users', '0019_rename_admin_to_administrator'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentSession',
            fields=[
                ('session_id', models.CharField(help_text='Format: asmt_{uuid4}', max_length=80, primary_key=True, serialize=False)),
                ('topic_name', models.CharField(blank=True, max_length=255)),
                ('num_questions_requested', models.IntegerField()),
                ('num_questions_returned', models.IntegerField(blank=True, help_text='Actual number of valid questions the AI returned', null=True)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('GENERATING', 'Generating'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='CREATED', max_length=20)),
                ('ai_model_used', models.CharField(blank=True, max_length=50)),
                ('generation_time_ms', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_sessions', to='subjects.module')),
                ('class_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_sessions', to='users.class')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_sessions', to='subjects.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Assessment Session',
                'verbose_name_plural': 'Assessment Sessions',
                'db_table': 'assessment_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PdfReference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('file_name', models.CharField(max_length=255)),
                ('gcs_path', models.CharField(help_text='GCS path: gs://gyaanbuddy-media/pdfs/{class}/{subject}/{chapter}/{filename}.pdf', max_length=500)),
                ('file_hash', models.CharField(blank=True, help_text='SHA-256 of file bytes — used to skip duplicate uploads', max_length=64)),
                ('total_pages', models.IntegerField(blank=True, null=True)),
                ('embedding_status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdfs', to='subjects.module')),
            ],
            options={
                'verbose_name': 'PDF Reference',
                'verbose_name_plural': 'PDF References',
                'db_table': 'pdf_references',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionModification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(help_text='Client-side question identifier (e.g. q_<uuid4> assigned by ai-service)', max_length=80)),
                ('modification_type', models.CharField(choices=[('REPHRASE', 'Rephrase'), ('CHANGE_DIFFICULTY', 'Change Difficulty'), ('CHANGE_OPTIONS', 'Change Options'), ('REGENERATE', 'Regenerate'), ('CUSTOM', 'Custom')], max_length=20)),
                ('user_instruction', models.TextField(blank=True)),
                ('original_snapshot', models.JSONField(help_text='Full question JSON before modification')),
                ('modified_snapshot', models.JSONField(help_text='Full question JSON after modification')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifications', to='subjects.assessmentsession')),
            ],
            options={
                'verbose_name': 'Question Modification',
                'verbose_name_plural': 'Question Modifications',
                'db_table': 'question_modifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session', 'question_id'], name='qmod_session_q_idx')],
            },
        ),
    ]
