// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDF7v_TVnyuxx_jV_Mian1MVwdM6BewSrU',
    appId: '1:130750342442:web:4444638cbcd4b79e12ea53',
    messagingSenderId: '130750342442',
    projectId: 'gyaanbuddy-600f2',
    authDomain: 'gyaanbuddy-600f2.firebaseapp.com',
    storageBucket: 'gyaanbuddy-600f2.firebasestorage.app',
    measurementId: 'G-0WQG53NYCB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDu-n5gUYvuEmXnIodKaR4LV2Ojn_R58x0',
    appId: '1:130750342442:android:096b120e151198a112ea53',
    messagingSenderId: '130750342442',
    projectId: 'gyaanbuddy-600f2',
    storageBucket: 'gyaanbuddy-600f2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnrW85oaH--ADEHa9k0uO9Mgw9M3G9LQU',
    appId: '1:130750342442:ios:5aa3a19a67e6b10d12ea53',
    messagingSenderId: '130750342442',
    projectId: 'gyaanbuddy-600f2',
    storageBucket: 'gyaanbuddy-600f2.firebasestorage.app',
    iosBundleId: 'com.prime.educare.gyan.buddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnrW85oaH--ADEHa9k0uO9Mgw9M3G9LQU',
    appId: '1:130750342442:ios:43539b4c617fe6c212ea53',
    messagingSenderId: '130750342442',
    projectId: 'gyaanbuddy-600f2',
    storageBucket: 'gyaanbuddy-600f2.firebasestorage.app',
    iosBundleId: 'com.example.quizy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDF7v_TVnyuxx_jV_Mian1MVwdM6BewSrU',
    appId: '1:130750342442:web:e7e5d87192d116e412ea53',
    messagingSenderId: '130750342442',
    projectId: 'gyaanbuddy-600f2',
    authDomain: 'gyaanbuddy-600f2.firebaseapp.com',
    storageBucket: 'gyaanbuddy-600f2.firebasestorage.app',
    measurementId: 'G-8Y6GWN8E4X',
  );

}